from Klasa import Vector

v1 = Vector()
v2 = Vector()
v3 = Vector(2)
print("Wektor towrzony bez zadanej wartosc",v1,"\nWektoer stworzony poprzez zadanie 2 czyli skladajacy sie z dwoch elementow",v3,'\n')
v1.LosowaGeneracja()
v2.LosowaGeneracja()
print("Wspolrzedne wektora po losowej generacji jego elemetnwo",v1,'\n')
v1.Wczytywanie([1,2,3])
print("Wketor po wczytaniu [1,2,3] ",v1,'\n')
v1.Wczytywanie([0,0,0])
v1.LosowaGeneracja()
print("dwa wektroy ktore bedziemy dodawac",v1,v2,'\n')
print("Suma tych wektorow",v1+v2,'\n')
v1.LosowaGeneracja()
v2.LosowaGeneracja()
print("dwa wektoryu ktore bedziemy odejmowac",v1,v2,'\n')
print("roznica tych wektorow",v1-v2,'\n')
print("wektor ktory bedziemy ,mnozyc przez skalar a=3",v1,"\n")
print("Wektor po przemnozeniu przez skalar a=3",v1*3,'\n')
print("dlugosc wektora/ liczba elementow z ktorej sie sklada",v1.Dlugosc(),'\n')
print("Wektor ktorego elementy bedziemy dodawac",v2,"\n")
print("suma elementow tego wektora",v2.Suma(),'\n')
print("Wektory ktore bedziemy ,mnozyc skalarnie",v1,v2,"\n")
print("wynik ,nozenia skalarnego tych wektorow",v1.IloczynSkalarny(v2),'\n')
print("Drugi element wektora",v1,"to",v1[1],'\n')
v1.Wczytywanie([1,2,3])
print("Sparwdzanie czy w wektorze",v1,"znajduje sie 1",1 in v1,'\n')
print("Sparwdzanie czy w wektorze",v1,"znajduje sie 10",10 in v1,'\n')